### ISSUE TITLE
Decrease margins on OUSD blog

### ISSUE THREAD

**Issue by rmcn15** [OriginProtocol/ousd.com#113] opened 2023-03-20 19:02 UTC
When clicking on an OUSD blog post the text loads very narrowly in small font. 

Being that our rankings are increasing, the time on page will start to matter more for SEO. Increasing the text size and decreasing the margins should increase avg time on page as the content will be easier to consume.

Example link: https://www.ousd.com/stablecoin-interest-rates 

Example of decreased margins: https://www.originprotocol.com/origin-welcomes-scott-mitchell

**Comment by micahalcorn** [comment] 2023-07-28 19:21
I believe this is a duplicate of https://github.com/OriginProtocol/ousd.com/issues/171 but please reopen if there's still an issue.

**Closed by micahalcorn** 2023-07-28 19:21 UTC
